apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-catalog
resources:
  - ../../base
components:
  - ../../components/postgres-db
patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["packages/backend", "--config", "app-config.yaml", "--config", "app-config.dev.yaml"]
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "development"
    target:
      kind: Deployment
      name: service-catalog
patchesStrategicMerge:
  - route.yaml
images:
  - name: quay.io/operate-first/service-catalog
    newName:
    newTag:
