apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-catalog
resources:
  - ../../base
components:
  - ../../components/postgres-db
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: app-config.dev.yaml
      - op: add
        path: /spec/template/spec/containers/0/env/0/value
        value: development
    target:
      kind: Deployment
      name: service-catalog
patchesStrategicMerge:
  - route.yaml
  - secret.yaml
images:
  - name: quay.io/operate-first/service-catalog
    newName:
    newTag:
