apiVersion: v1
kind: Secret
metadata:
  name: service-catalog
  annotations:
    kustomize.config.k8s.io/behavior: replace
stringData:
  BACKEND_SECRET: secret
  ARGOCD_AUTH_TOKEN:
  AUTH_GITHUB_CLIENT_ID:
  AUTH_GITHUB_CLIENT_SECRET:
