apiVersion: v1
kind: Secret
metadata:
    name: service-catalog
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    BACKEND_SECRET: ENC[AES256_GCM,data:5ZuDTp6HN/o2E68LUz9YbWUNAdtRwUqfw1wDVXRyMGs=,iv:D21drH7ECBCiaDMZTb+F/W/PsG87pXx2mfZD0XD3IIA=,tag:tPZ9IpIDKO1f/22Gpb0eBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T10:05:05Z"
    mac: ENC[AES256_GCM,data:dGkHFKkND4U6uIt5CJP3B52a7Ev+h3zivkCtrSWQ53AVYQPETRELi276E5vNcyBHUeSoELBVU2vls0G/OJR3Bha3cYARnc83LfkGy7Fhgf3ixgTjc4nHItVlOyw8kZnnDmC2sQrmbT5oQlcNif5UfeZNNwky8MaqKVoWJCEt2X4=,iv:UZxKPiS9QeZkRSdTPUgXisjMECc7wrDbK5xV6b93Cps=,tag:uKv7BXc0o46qhSFrMOa+8Q==,type:str]
    pgp:
        - created_at: "2022-06-16T11:01:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAi19LuhPMQ0N62ButZYBAtYoWIapryDoY4xpSIN4dkVU7
            4fqi6nrfTw82jeGh8ueREXBdR9m1auwd0IHeoJOTe2X+ylHib7/DkqWr55oKdlg7
            5Ju7AhW70Isp0islG4bAOQw4+9vPREM94DzvG4TrLGELt5pD3/CZ+Z/IpBzMry9B
            LuYgoRxhjibIr1HS35Nenp7oH+XlXZALxZgyW80xoW9aVVUxwtDXfqZNJxUaB+eN
            Ic8oNVDz/EpWnce9IHyS1XHm7wiL+BFzMX/PlXcaQCfwbAal8GARn1qtoSKNB+N1
            LgKATuX7kD00izm7tAsaqxETtZ2mBk3oUXCdG7mFAfUkxdO2PFygFszVrMGQzujn
            BEjyMhdf+Kd0YhRQ4m4Dqy9W1MXl6NPge2o/rY2TEaSHMrxtnr94tW2oKaotqUa2
            audiDT+b8t32j3IgqDueOO6f3JYHzR87edtlxiQ48plfRF4ay2WzVQH+xa7A4VrM
            fDJM/F2e0yiwRDetNUbb2F1ajROdxVH3UKSeGgrAqbEL992ykowqf1olVQLiOY/p
            iiHmRlar91W39x9BDlL+xIjUvk6VC8M4S4PJomZ39JkebgvTTT5gcU7idwyAVURS
            Ti54IANcDWzJY4/6jK/Ec20e5DSUBcUa/Q0EXrxDW/lgt+JHiJG7hSS/hUDu7enS
            UQFuq91k0r+dlZLb6LV3l+ZEg0DFWtw5V1R0GrsU5FB9xR8090C5DAg8QVdv8n1x
            /1pqx3ShJdCul0LMVKqe0X0g9uSV4sqGFj+Yy/Zn1dTxBg==
            =Z/fe
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
