apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-catalog
  template:
    metadata:
      labels:
        app: service-catalog
    spec:
      serviceAccountName: service-catalog-k8s-plugin
      containers:
        - name: service-catalog
          image: service-catalog
          command: ["node"]
          args:
            - packages/backend
            - --config
            - app-config.yaml
            - --config
          ports:
            - containerPort: 7007
          envFrom:
            - secretRef:
                name: service-catalog-pguser-service-catalog
          env:
            - name: NODE_ENV
            - name: BACKEND_SECRET
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: BACKEND_SECRET
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: ARGOCD_AUTH_TOKEN
            - name: AUTH_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: AUTH_GITHUB_CLIENT_ID
            - name: AUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: AUTH_GITHUB_CLIENT_SECRET
            - name: GRAFANA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-catalog
                  key: GRAFANA_TOKEN
          volumeMounts:
            - name: ca-cert
              mountPath: "/mnt/certs"
      volumes:
        - name: ca-cert
          secret:
            secretName: service-catalog-cluster-cert
            items:
              - key: ca.crt
                path: ca.crt
      resources:
        limits:
          cpu: 300m
        requests:
          cpu: 200m
