apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-catalog
  template:
    metadata:
      labels:
        app: service-catalog
    spec:
      containers:
        - name: service-catalog
          image: service-catalog
          command: ["node"]
          args: []  # added by patch in overlays
          imagePullPolicy: Always
          ports:
            - containerPort: 7007
          envFrom:
            - secretRef:
                name: service-catalog-pguser-service-catalog
            - secretRef:
                name: service-catalog
          env:
          - name: NODE_ENV
            value: ""  # added by patch in overlays
          volumeMounts:
          - name: ca-cert
            mountPath: "/mnt/certs"
      volumes:
      - name: ca-cert
        secret:
          secretName: service-catalog-cluster-cert
          items:
          - key: ca.crt
            path: ca.crt
