apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-catalog
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - route-webterminal.yaml
  - postgres.yaml
  - serviceaccount.yaml
commonLabels:
  app.kubernetes.io/name: service-catalog
  app.kubernetes.io/managed-by: sig-services
images:
  - name: service-catalog
    newName: quay.io/operate-first/service-catalog
  - name: webterminal
    newName: quay.io/operate-first/webterminal
