apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - secret.yaml
  - postgres.yaml
images:
- name: service-catalog
  newName: quay.io/operate-first/service-catalog
