apiVersion: v1
kind: Service
metadata:
  name: service-catalog
spec:
  selector:
    app.kubernetes.io/component: app
  ports:
    - name: service-catalog
      port: 7007
      targetPort: 7007
    - name: webterminal
      port: 8080
      targetPort: 8080
