# Used in local develompment setup

app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  auth:
    keys:
      - $include: config.yaml#auth
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  rules:
    - allow:
        - Component
        - System
        - Location
        - User
        - Group
  locations:
    $include: config.yaml#catalog
