# Used in local develompment setup

app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: production
  providers:
    production:
      github:
        clientId: 2de370556fbda03ce24f
        clientSecret: 5d6aa421520e0ae159fba93de52ee4d73e85eb37
