# Used in local develompment setup

app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  auth:
    keys:
      - secret:  # Generated secret here
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

catalog:
  rules:
    - allow:
        - Component
        - System
        - Location
        - User
        - Group
  locations:
    - type: file
      target: ../../examples/all.yaml
    #  Uncomment to use defintions files from apps repo
    # - type: url
    #   target: https://github.com/SamoKopecky/apps/blob/master/service-catalog/all.yaml
