# Used in production setup on a k8s/openshift cluster

app:
  baseUrl: https://service-catalog.operate-first.cloud

backend:
  baseUrl: https://service-catalog.operate-first.cloud
  database:
    client: pg
    connection:
      host: ${host}
      user: ${user}
      password: ${password}
      port: ${port}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca:
          $file: /mnt/certs/ca.crt
  cors:
    origin: https://service-catalog.operate-first.cloud
