site_name: "Service Catalog documentation"

nav:
  - Home: index.md
  - Configuring catalog entities: configuring-entities.md
  - Contributing and development setup: contributing.md
  - Kubernetes plugin configuration: k8s-plugin-configuration.md
  - OCM (Open Cluster Management) plugin: ocm-plugin.md

plugins:
  - techdocs-core
  - search
  - kroki
