apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Services
  description: A collection of all operate-first services
spec:
  targets:
    - components/argo.yaml
    - components/dex.yaml
    - components/grafana.yaml
    - components/observatorium.yaml
    - components/opendatahub.yaml
    - components/openshift.yaml