apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["packages/backend", "--config", "app-config.yaml", "--config", "app-config.prod.yaml"]
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "production"
    target:
      kind: Deployment
      name: backstage
  - patch: |
      - op: remove
        path: /spec/tls
      - op: remove
        path: /spec/wildcardPolicy
      - op: add
        path: /metadata/annotations
        value:
          kubernetes.io/tls-acme: "true"
    target:
      kind: Route
      name: backstage
