name: Build Service Catalog
description: Build Service Catalog container as an S2I image
inputs:
  tags:
    description: Tags of the image; default is github SHA
    default: ${{ github.sha }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Install S2I
      shell: bash
      run: |
        mkdir -p ~/.local/bin
        curl \
          https://api.github.com/repos/openshift/source-to-image/releases/latest | \
          grep "browser_download_url.*linux-amd64" | cut -d '"' -f 4 | \
          wget -qO - -i - | tar xzv -C ~/.local/bin

    - name: S2I Build
      shell: bash
      run: ./packages/backend/build-image.sh "${{ inputs.tags }}"
