name: Send dispatch to publisher

on:
  push:
    branches:
      - main
    paths:
      - "**/docs/**"
      - "mkdocs.yaml"
      - "mkdocs.yml"

jobs:
  send-repo-dispatches:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch for service-catalog
        uses: operate-first/service-catalog/.github/actions/docs-dispatch@main
        with:
          docs_path: '.'
          entity_name: 'service-catalog'
          entity_kind: 'Component'
          repository: ${{ github.repository }}
          token: ${{ secrets.SESHETA_TOKEN }}
